### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by teddyrendahl** [conda-forge/ophyd-feedstock#7]
Would you mind running this to get a Python 3.7 build of`ophyd`?

**Comment by CJ-Wright** [comment]
There is an open PR for this but I haven't gotten a chance to fix the Sha. Would you be interested in being a maintainer?

**Comment by klauer** [comment]
What needs to be done in the PR, @CJ-Wright?

**Comment by CJ-Wright** [comment]
I fixed it. The sha moved because we are using GitHub's tarball rather than uploading one to the GitHub release https://github.com/conda-forge/ophyd-feedstock/pull/6/commits/162c46e1b938860d4b3144de1e5ac28291cfd8ae

**Comment by klauer** [comment]
OK, great! Looks like the PR removes 3.5 as well: this is good as we're soon going to remove support from ophyd.

**Comment by hhslepicka** [comment]
Package is noarch and available for Python 3.7. Closing
